### ISSUE TITLE
Operation cannot be fulfilled on deployments.apps

### ISSUE THREAD

**Issue by SS30723** [jaegertracing/jaeger-operator#1165]
Hi, I am still getting this error 'Operation cannot be fulfilled on deployments.apps'. I have used auto side car injection as given in the example, deploy/examples/business-application-injected-sidecar.yaml.
I see the UI is up and running and I am able to view jaeger-query service, but the calls related to my app is not coming up on the UI. Is it because of the above error?

**Comment by jpkrohling** [comment]
I just tried it out, and it seems to work for me. My environment (created using minikube): 

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0-4-g38212b5", GitCommit:"d038424d6d4f1cc39ad586ac0d36dac3a7a37ceb", GitTreeState:"clean", BuildDate:"2020-06-16T03:29:46Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Here are the steps I used (the first ones are the same as the readme):
```
kubectl create namespace observability
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/service_account.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role_binding.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/operator.yaml
```

Once the operator is ready:

```
kubectl apply -f deploy/examples/simplest.yaml  -n observability
```

And once the reconciliation is done (or when the Jaeger instance is ready):

```
kubectl apply -f deploy/examples/business-application-injected-sidecar.yaml  -n observability
```

Once the deployment with the business application is ready:

```
kubectl port-forward -n observability deployments/myapp 8080
curl localhost:8080
```

The following should be seen in the Jaeger UI. The address is `http://ingress-ip`.  The IP can be found via: `kubectl get ingress -n observability`

![image](https://user-images.githubusercontent.com/13387/91019691-b680e100-e5f1-11ea-99b7-60dba7432390.png)

**Comment by SS30723** [comment]
Thanks for replying. I have deployed this in a kubernetes cluster that already has ingress. So I disabled ingress while creating jaeger CRD (ingress --> enabled --> false). I am able to see the jaeger UI, but I dont see the application traffic coming in. 
Couple of questions
1. Should I do a port forward? what is the use of it?because I have defined the UI in kubernetes cluster ingress and I am able to access it
2. I see the following services /api/services, /api/services/{service}/operation and /api/traces. I am not seeing traffic related to my application.

**Comment by jpkrohling** [comment]
1. the port-forward to the business application was just for development purposes. In a real cluster, you'd have your application exposed via a proper ingress.
2. those are `operations`, the service is likely `jaeger-query`. Those are traces related to the Jaeger UI itself.

At this point, all I can offer you is the troubleshooting guide: https://www.jaegertracing.io/docs/1.18/troubleshooting/ . If you still can't get it working after following that, let us know, along with the information you got while troubleshooting (especially logs).

**Comment by jpkrohling** [comment]
@SS30723 were your questions answered? Can this be closed?

**Comment by arushi09-hub** [comment]
Hi @jpkrohling I think i am also stuck in the same issue. Tried out the process in the similar manner as you presented it down. But I am also still not able to see my application on the UI. I have checked the jaeger-operator logs which earlier showed me some error of "Operation Cannot be fulfilled on deployments" But now after making deployment and  deploying jaeger instances in the same namespace. I don't get the error but still unable to see the application traces on UI
