### ISSUE TITLE
Operation cannot be fulfilled on deployments.apps...

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-operator#927]
While testing #914, I saw a message similar to the following in the logs. Trying it out with the latest master confirms that this exists there as well:

```
ERRO[0071] failed to update                              deployment="&Deployment{ObjectMeta:{myapp  default /apis/apps/v1/namespaces/default/deployments/myapp a86b37e2-2b22-4723-9327-6fb8cdfdc458 286277 1 2020-02-26 10:27:50 +0100 CET <nil> <nil> map[sidecar.jaegertracing.io/injected:simple-prod] map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{\"sidecar.jaegertracing.io/inject\":\"true\"},\"name\":\"myapp\",\"namespace\":\"default\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"myapp\"}},\"template\":{\"metadata\":{\"annotations\":{\"sidecar.istio.io/inject\":\"true\"},\"labels\":{\"app\":\"myapp\"}},\"spec\":{\"containers\":[{\"image\":\"jaegertracing/vertx-create-span:operator-e2e-tests\",\"name\":\"myapp\",\"ports\":[{\"containerPort\":8080,\"protocol\":\"TCP\"}]}]}}}}\n prometheus.io/port:5778 prometheus.io/scrape:true sidecar.jaegertracing.io/inject:simple-prod] [] []  []},Spec:DeploymentSpec{Replicas:*1,Selector:&v1.LabelSelector{MatchLabels:map[string]string{app: myapp,},MatchExpressions:[]LabelSelectorRequirement{},},Template:{{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[app:myapp] map[sidecar.istio.io/inject:true] [] []  []} {[] [] [{myapp jaegertracing/vertx-create-span:operator-e2e-tests [] []  [{ 0 8080 TCP }] [] [{JAEGER_SERVICE_NAME myapp.default nil} {JAEGER_PROPAGATION jaeger,b3 nil}] {map[] map[]} [] [] nil nil nil nil /dev/termination-log File IfNotPresent nil false false false} {jaeger-agent jaegertracing/jaeger-agent:1.16.0 [] [--jaeger.tags=cluster=undefined,deployment.name=myapp,pod.namespace=default,pod.name=${POD_NAME:},host.ip=${HOST_IP:},container.name=myapp --reporter.grpc.host-port=dns:///simple-prod-collector-headless.default:14250 --reporter.type=grpc]  [{zk-compact-trft 0 5775 UDP } {config-rest 0 5778  } {jg-compact-trft 0 6831 UDP } {jg-binary-trft 0 6832 UDP }] [] [{POD_NAME  EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:,FieldPath:metadata.name,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {HOST_IP  &EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:,FieldPath:status.hostIP,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}}] {map[] map[]} [] [] nil nil nil nil    nil false false false}] [] Always 0xc0011e6a80 <nil> ClusterFirst map[]   <nil>  false false false <nil> &PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,RunAsGroup:nil,Sysctls:[]Sysctl{},WindowsOptions:nil,} []   nil default-scheduler [] []  <nil> nil [] <nil> <nil> <nil> map[] []}},Strategy:DeploymentStrategy{Type:RollingUpdate,RollingUpdate:&RollingUpdateDeployment{MaxUnavailable:25%,MaxSurge:25%,},},MinReadySeconds:0,RevisionHistoryLimit:*10,Paused:false,ProgressDeadlineSeconds:*600,},Status:DeploymentStatus{ObservedGeneration:0,Replicas:0,UpdatedReplicas:0,AvailableReplicas:0,UnavailableReplicas:0,Conditions:[]DeploymentCondition{},ReadyReplicas:0,CollisionCount:nil,},}" error="Operation cannot be fulfilled on deployments.apps \"myapp\": the object has been modified; please apply your changes to the latest version and try again"
```

This can be reproduced by deploying our example `deploy/examples/business-application-injected-sidecar.yaml`:
https://github.com/jaegertracing/jaeger-operator/blob/d80bd242d8c3a4894b504a0e5f00de2b0c3730c8/deploy/examples/business-application-injected-sidecar.yaml#L1-L23

@rubenvp8510 would you be able to look into this one?

**Comment by rubenvp8510** [comment]
Yes, I'll take a look.

**Comment by rubenvp8510** [comment]
@jpkrohling is this still an issue? Or was fixed via https://github.com/jaegertracing/jaeger-operator/pull/940 ?

**Comment by jpkrohling** [comment]
I believe this was fixed.

**Comment by 172prateek** [comment]
@SS30723  I am also facing same issue... and doing exactly same what you have done. have you got nay resolution in it..

**Comment by Andycharalambous** [comment]
Having same problem - jaeger-operator v1.28.0. Upgraded yesterday to fix a few other bugs we had with correct collector selection in sidecar injector. Now none of our deployments get injected with latest version of jaeger-agent.

**Comment by purvaldur** [comment]
Also having the same problem after an upgrade to v1.27.0 to fix another bug. I've temporarily degraded back to 1.24 since the error I'm getting on 1.24 is non-blocking at the moment.

**Comment by violinorg** [comment]
Having same problem - jaeger-operator v1.36.0. Yesterday was updated along with the cluster components. Previously on v1.35.0 there were no problems. Reverting the version didn't fix the problem
